export const CATALOG = {
  // ── WEBSITE DESIGN & BUILD ────────────────────────────────────────────────
  'basic-launch-website': { group: 'website', icon: 'Rocket', amount: 450, recurring: false, unit: 'oneoff',
    label: { EN: 'Starter Website', GR: 'Starter Ιστοσελίδα' }, price: { EN: '€450 one-off', GR: '€450 εφάπαξ' },
    best: { EN: 'Small local businesses, cafés, salons, trades and early-stage businesses', GR: 'Μικρές τοπικές επιχειρήσεις, καφέ, κομμωτήρια, μάστορες και νέες επιχειρήσεις' },
    desc: { EN: 'A clean, professional website for small businesses that need to get online quickly and look credible.', GR: 'Μια καθαρή, επαγγελματική ιστοσελίδα για μικρές επιχειρήσεις που θέλουν να μπουν online γρήγορα και αξιόπιστα.' } },
  'business-website': { group: 'website', icon: 'LayoutTemplate', amount: 750, recurring: false, unit: 'oneoff', popular: true,
    label: { EN: 'Business Website', GR: 'Business Ιστοσελίδα' }, price: { EN: '€750 one-off', GR: '€750 εφάπαξ' },
    best: { EN: 'Villas, restaurants, gyms, clinics, tourism businesses and growing local businesses', GR: 'Βίλες, εστιατόρια, γυμναστήρια, κλινικές, τουριστικές και αναπτυσσόμενες τοπικές επιχειρήσεις' },
    desc: { EN: 'A stronger business website with better structure, more content sections, an enquiry flow, and room to add automation or marketing support.', GR: 'Μια πιο δυνατή επαγγελματική ιστοσελίδα με καλύτερη δομή, περισσότερες ενότητες, ροή αιτημάτων και χώρο για αυτοματισμούς ή marketing.' } },
  'growth-website': { group: 'website', icon: 'TrendingUp', amount: 1200, recurring: false, unit: 'oneoff',
    label: { EN: 'Growth Website', GR: 'Growth Ιστοσελίδα' }, price: { EN: '€1,200 one-off', GR: '€1.200 εφάπαξ' },
    best: { EN: 'Established businesses ready to scale with stronger design and lead generation', GR: 'Εδραιωμένες επιχειρήσεις έτοιμες να αναπτυχθούν με ισχυρότερο σχεδιασμό και lead generation' },
    desc: { EN: 'A complete growth-focused website with advanced structure, conversion-optimised pages, SEO foundations and automation-ready setup.', GR: 'Μια ολοκληρωμένη ιστοσελίδα με στόχο την ανάπτυξη, προηγμένη δομή, βελτιστοποιημένες σελίδες μετατροπών και έτοιμη για αυτοματισμούς.' } },
  'premium-ai-website': { group: 'website', icon: 'Sparkles', amount: 0, recurring: false, unit: 'quote',
    label: { EN: 'Premium AI-Ready Website', GR: 'Premium AI-Ready Ιστοσελίδα' }, price: { EN: 'Quote required', GR: 'Κατόπιν συνεννόησης' },
    best: { EN: 'Businesses that want a higher-end website, AI automation, proposal journeys and WhatsApp flows', GR: 'Επιχειρήσεις που θέλουν premium ιστοσελίδα, AI αυτοματισμούς, διαδρομές προτάσεων και ροές WhatsApp' },
    desc: { EN: 'A more advanced website with premium design, a stronger customer journey, AI assistant support and automation-ready sections for scalable growth.', GR: 'Μια πιο προηγμένη ιστοσελίδα με premium σχεδιασμό, ισχυρότερη διαδρομή πελάτη, υποστήριξη AI βοηθού και έτοιμες ενότητες αυτοματισμού για κλιμακούμενη ανάπτυξη.' } },

  // ── DIGITAL SERVICES ─────────────────────────────────────────────────────
  'seo': { group: 'digital', icon: 'Search', amount: 150, recurring: true, unit: 'month',
    label: { EN: 'SEO', GR: 'SEO' }, price: { EN: '€150/month', GR: '€150/μήνα' },
    best: { EN: 'All local businesses wanting more Google visibility', GR: 'Τοπικές επιχειρήσεις που θέλουν περισσότερη ορατότητα στο Google' },
    desc: { EN: 'Ongoing search engine optimisation to improve your Google rankings and attract more organic traffic.', GR: 'Συνεχής βελτιστοποίηση για μηχανές αναζήτησης για καλύτερες θέσεις στο Google.' } },
  'whatsapp-automation-svc': { group: 'digital', icon: 'MessageSquare', amount: 150, recurring: true, unit: 'month',
    label: { EN: 'WhatsApp Automation', GR: 'WhatsApp Αυτοματισμός' }, price: { EN: '€250 setup + €150/month', GR: '€250 εγκατάσταση + €150/μήνα' },
    best: { EN: 'Businesses that take enquiries via WhatsApp', GR: 'Επιχειρήσεις που δέχονται αιτήματα μέσω WhatsApp' },
    desc: { EN: 'Full WhatsApp automation setup — enquiry flows, automated replies, lead capture and monthly management.', GR: 'Πλήρης αυτοματισμός WhatsApp — ροές αιτημάτων, αυτόματες απαντήσεις, λήψη leads και μηνιαία διαχείριση.' } },
  'email-automation-svc': { group: 'digital', icon: 'Mail', amount: 100, recurring: true, unit: 'month',
    label: { EN: 'Email Automation', GR: 'Email Αυτοματισμός' }, price: { EN: '€150 setup + €100/month', GR: '€150 εγκατάσταση + €100/μήνα' },
    best: { EN: 'Businesses wanting automated follow-ups and email sequences', GR: 'Επιχειρήσεις που θέλουν αυτόματα follow-up και ακολουθίες email' },
    desc: { EN: 'Email automation setup with welcome sequences, follow-ups, reminders and monthly management.', GR: 'Στήσιμο αυτοματισμού email με ακολουθίες καλωσορίσματος, follow-up, υπενθυμίσεις και μηνιαία διαχείριση.' } },
  'video-websites': { group: 'digital', icon: 'Video', amount: 500, recurring: false, unit: 'oneoff',
    label: { EN: 'Video Websites', GR: 'Video Ιστοσελίδες' }, price: { EN: '€500 one-off', GR: '€500 εφάπαξ' },
    best: { EN: 'Businesses that want video-first landing pages or hero sections', GR: 'Επιχειρήσεις που θέλουν σελίδες με video ως κεντρικό στοιχείο' },
    desc: { EN: 'A website or landing page built around video content for maximum impact and engagement.', GR: 'Ιστοσελίδα ή landing page χτισμένη γύρω από video για μέγιστο αντίκτυπο και engagement.' } },
  'ai-prompts': { group: 'digital', icon: 'Bot', amount: 200, recurring: false, unit: 'oneoff',
    label: { EN: 'AI Prompts', GR: 'AI Prompts' }, price: { EN: '€200 one-off', GR: '€200 εφάπαξ' },
    best: { EN: 'Businesses wanting ready-to-use AI prompts for marketing and operations', GR: 'Επιχειρήσεις που θέλουν έτοιμα AI prompts για marketing και λειτουργίες' },
    desc: { EN: 'A custom set of AI prompts tailored to your business for content, replies, proposals and daily tasks.', GR: 'Προσαρμοσμένα AI prompts για την επιχείρησή σας για περιεχόμενο, απαντήσεις, προτάσεις και καθημερινές εργασίες.' } },
  'social-media-content': { group: 'digital', icon: 'Instagram', amount: 150, recurring: true, unit: 'month',
    label: { EN: 'Social Media Content', GR: 'Περιεχόμενο Social Media' }, price: { EN: '€150/month', GR: '€150/μήνα' },
    best: { EN: 'Businesses wanting consistent social media presence', GR: 'Επιχειρήσεις που θέλουν σταθερή παρουσία στα social media' },
    desc: { EN: 'Monthly social media content creation and scheduling across your key platforms.', GR: 'Μηνιαία δημιουργία και προγραμματισμός περιεχομένου social media στις βασικές πλατφόρμες σας.' } },
  'ai-content-marketing': { group: 'digital', icon: 'Megaphone', amount: 250, recurring: true, unit: 'month',
    label: { EN: 'AI Content and Marketing', GR: 'AI Περιεχόμενο & Marketing' }, price: { EN: '€250/month', GR: '€250/μήνα' },
    best: { EN: 'Businesses wanting AI-powered content and marketing campaigns', GR: 'Επιχειρήσεις που θέλουν AI-powered περιεχόμενο και καμπάνιες marketing' },
    desc: { EN: 'AI-assisted content creation, social posts, email campaigns and marketing copy every month.', GR: 'AI-υποστηριζόμενη δημιουργία περιεχομένου, social posts, email καμπάνιες και marketing copy κάθε μήνα.' } },
  'ai-automation-svc': { group: 'digital', icon: 'Workflow', amount: 100, recurring: true, unit: 'month',
    label: { EN: 'AI Automation', GR: 'AI Αυτοματισμός' }, price: { EN: '€150 setup + €100/month', GR: '€150 εγκατάσταση + €100/μήνα' },
    best: { EN: 'Businesses wanting to automate repetitive tasks with AI', GR: 'Επιχειρήσεις που θέλουν να αυτοματοποιήσουν επαναλαμβανόμενες εργασίες με AI' },
    desc: { EN: 'AI automation setup for your business processes — forms, enquiries, scheduling and task management.', GR: 'Στήσιμο AI αυτοματισμού για τις διαδικασίες σας — φόρμες, αιτήματα, προγραμματισμός και διαχείριση εργασιών.' } },
  'ai-avatar-video': { group: 'digital', icon: 'Clapperboard', amount: 0, recurring: false, unit: 'quote',
    label: { EN: 'AI Avatar and Video Content', GR: 'AI Avatar & Video Περιεχόμενο' }, price: { EN: 'Quote required', GR: 'Κατόπιν συνεννόησης' },
    best: { EN: 'Businesses wanting AI-generated video content and avatars', GR: 'Επιχειρήσεις που θέλουν AI-generated video περιεχόμενο και avatars' },
    desc: { EN: 'Custom AI avatar creation and AI-generated video content for your brand and marketing.', GR: 'Δημιουργία προσαρμοσμένου AI avatar και AI-generated video περιεχόμενο για την επωνυμία και το marketing σας.' } },
  'proposal-sales-docs': { group: 'digital', icon: 'FileCheck', amount: 200, recurring: false, unit: 'oneoff',
    label: { EN: 'Proposal and Sales Documents', GR: 'Προτάσεις & Έγγραφα Πωλήσεων' }, price: { EN: '€200 one-off', GR: '€200 εφάπαξ' },
    best: { EN: 'Businesses wanting professional proposal and sales document templates', GR: 'Επιχειρήσεις που θέλουν επαγγελματικά πρότυπα προτάσεων και εγγράφων πωλήσεων' },
    desc: { EN: 'Professionally designed proposal and sales document templates built for your business and services.', GR: 'Επαγγελματικά σχεδιασμένα πρότυπα προτάσεων και εγγράφων πωλήσεων προσαρμοσμένα στην επιχείρησή σας.' } },

  // ── DIGITAL MARKETING ─────────────────────────────────────────────────────
  'landing-page': { group: 'marketing', icon: 'FileText', amount: 350, recurring: false, unit: 'oneoff',
    label: { EN: 'Landing Page Design', GR: 'Σχεδιασμός Landing Page' }, price: { EN: '€350 one-off', GR: '€350 εφάπαξ' },
    best: { EN: 'Offers, bookings & seasonal campaigns', GR: 'Προσφορές, κρατήσεις & εποχικές καμπάνιες' },
    desc: { EN: 'A focused single page for a specific offer, booking push or lead-generation campaign.', GR: 'Μία εστιασμένη σελίδα για συγκεκριμένη προσφορά, κράτηση ή καμπάνια lead generation.' } },
  'extra-page': { group: 'marketing', icon: 'Plus', amount: 150, recurring: false, unit: 'oneoff',
    label: { EN: 'Extra Website Page', GR: 'Επιπλέον Σελίδα' }, price: { EN: '€150 one-off', GR: '€150 εφάπαξ' },
    best: { EN: 'Adding pages to an existing site', GR: 'Προσθήκη σελίδων σε υπάρχον site' },
    desc: { EN: 'An additional designed and written page added to your website.', GR: 'Μια επιπλέον σχεδιασμένη και γραμμένη σελίδα στο site σας.' } },
  'brand-identity': { group: 'marketing', icon: 'Palette', amount: 450, recurring: false, unit: 'oneoff',
    label: { EN: 'Brand Identity Starter Pack', GR: 'Brand Identity Starter Pack' }, price: { EN: '€450 one-off', GR: '€450 εφάπαξ' },
    best: { EN: 'New businesses & rebrands', GR: 'Νέες επιχειρήσεις & rebranding' },
    desc: { EN: 'Logo, colours, typography and visual direction to look more professional.', GR: 'Λογότυπο, χρώματα, τυπογραφία και οπτική κατεύθυνση για πιο επαγγελματική εικόνα.' } },
  'local-seo-setup': { group: 'marketing', icon: 'MapPin', amount: 200, recurring: false, unit: 'oneoff',
    label: { EN: 'Local SEO Setup', GR: 'Τοπικό SEO Setup' }, price: { EN: '€200 one-off', GR: '€200 εφάπαξ' },
    best: { EN: 'All local businesses wanting better local search visibility', GR: 'Τοπικές επιχειρήσεις που θέλουν καλύτερη τοπική ορατότητα' },
    desc: { EN: 'One-off local SEO setup: Google Business optimisation, local keyword targeting and technical SEO foundations.', GR: 'Εφάπαξ στήσιμο τοπικού SEO: βελτιστοποίηση Google Business, στόχευση τοπικών λέξεων και τεχνικά θεμέλια SEO.' } },
  'gbp-support': { group: 'marketing', icon: 'Star', amount: 100, recurring: true, unit: 'month',
    label: { EN: 'Google Business Profile Support', GR: 'Υποστήριξη Google Business Profile' }, price: { EN: '€100/month', GR: '€100/μήνα' },
    best: { EN: 'Restaurants, cafés, salons, gyms', GR: 'Εστιατόρια, καφετέριες, κομμωτήρια, γυμναστήρια' },
    desc: { EN: 'Keep your Google profile optimised with photos, posts and up-to-date info.', GR: 'Κρατά το προφίλ Google βελτιστοποιημένο με φωτογραφίες, posts και ενημερωμένες πληροφορίες.' } },
  'google-ads': { group: 'marketing', icon: 'MousePointerClick', amount: 150, recurring: true, unit: 'month',
    label: { EN: 'Local Google Ads Management', GR: 'Διαχείριση Τοπικών Google Ads' }, price: { EN: '€150/month', GR: '€150/μήνα' },
    best: { EN: 'Tourism, car & boat hire, villas', GR: 'Τουρισμός, ενοικιάσεις αυτοκινήτων & σκαφών, βίλες' },
    desc: { EN: 'Set up and manage local campaigns that drive enquiries, bookings and calls. Ad spend not included.', GR: 'Στήσιμο και διαχείριση τοπικών καμπανιών για αιτήματα, κρατήσεις και κλήσεις. Δεν περιλαμβάνεται διαφημιστική δαπάνη.' } },
  'social-video': { group: 'marketing', icon: 'Video', amount: 200, recurring: true, unit: 'month',
    label: { EN: 'Social Video Content Support', GR: 'Υποστήριξη Social Video Περιεχομένου' }, price: { EN: '€200/month', GR: '€200/μήνα' },
    best: { EN: 'Restaurants, salons, tourism, villas', GR: 'Εστιατόρια, κομμωτήρια, τουρισμός, βίλες' },
    desc: { EN: 'Scripted, edited short-form videos and social content posted for you.', GR: 'Σύντομα βίντεο με σενάριο και μοντάζ και περιεχόμενο social, δημοσιευμένα για εσάς.' } },
  'analytics-reporting': { group: 'marketing', icon: 'BarChart3', amount: 100, recurring: true, unit: 'month',
    label: { EN: 'Analytics and Reporting', GR: 'Analytics & Αναφορές' }, price: { EN: '€100/month', GR: '€100/μήνα' },
    best: { EN: 'All industries', GR: 'Όλοι οι κλάδοι' },
    desc: { EN: 'Track visits, enquiries and conversions so you can see what is working.', GR: 'Παρακολουθεί επισκέψεις, αιτήματα και μετατροπές για να βλέπετε τι αποδίδει.' } },

  // ── AUTOMATION ────────────────────────────────────────────────────────────
  'whatsapp-automation': { group: 'automation', icon: 'MessageSquare', amount: 50, recurring: true, unit: 'month',
    label: { EN: 'WhatsApp Automation', GR: 'WhatsApp Αυτοματισμός' }, price: { EN: 'From €50/month', GR: 'Από €50/μήνα' },
    best: { EN: 'Villas, restaurants, salons, gyms, tourism', GR: 'Βίλες, εστιατόρια, κομμωτήρια, γυμναστήρια, τουρισμός' },
    desc: { EN: 'Structured WhatsApp enquiry flows, pre-filled messages, quick replies and lead capture.', GR: 'Δομημένες ροές αιτημάτων WhatsApp, προ-συμπληρωμένα μηνύματα, γρήγορες απαντήσεις και λήψη leads.' } },
  'ai-chatbot': { group: 'automation', icon: 'Bot', amount: 75, recurring: true, unit: 'month',
    label: { EN: 'AI Chatbot Setup', GR: 'Στήσιμο AI Chatbot' }, price: { EN: 'From €75/month', GR: 'Από €75/μήνα' },
    best: { EN: 'Villas, restaurants, gyms, tourism', GR: 'Βίλες, εστιατόρια, γυμναστήρια, τουρισμός' },
    desc: { EN: 'Guide visitors, answer common questions and push them to WhatsApp, booking or proposal.', GR: 'Καθοδηγεί επισκέπτες, απαντά σε ερωτήσεις και τους οδηγεί σε WhatsApp, κράτηση ή πρόταση.' } },
  'ai-proposal-generation': { group: 'automation', icon: 'FileText', amount: 75, recurring: true, unit: 'month',
    label: { EN: 'AI Proposal Generation', GR: 'Δημιουργία AI Προτάσεων' }, price: { EN: 'From €75/month', GR: 'Από €75/μήνα' },
    best: { EN: 'Tourism, villas, boat & car hire', GR: 'Τουρισμός, βίλες, ενοικιάσεις σκαφών & αυτοκινήτων' },
    desc: { EN: 'Automatically create tailored proposals from selected services and customer answers.', GR: 'Αυτόματη δημιουργία εξατομικευμένων προτάσεων από επιλεγμένες υπηρεσίες και απαντήσεις πελάτη.' } },
  'email-automation': { group: 'automation', icon: 'Mail', amount: 50, recurring: true, unit: 'month',
    label: { EN: 'Email Automation', GR: 'Email Αυτοματισμός' }, price: { EN: 'From €50/month', GR: 'Από €50/μήνα' },
    best: { EN: 'Villas, gyms, salons, tourism', GR: 'Βίλες, γυμναστήρια, κομμωτήρια, τουρισμός' },
    desc: { EN: 'Automate follow-ups, enquiry confirmations, reminders and nurture emails.', GR: 'Αυτοματοποιεί follow-up, επιβεβαιώσεις αιτημάτων, υπενθυμίσεις και emails καλλιέργειας.' } },
  'simple-automation': { group: 'automation', icon: 'Workflow', amount: 50, recurring: true, unit: 'month',
    label: { EN: 'Simple Business Automation', GR: 'Απλός Επιχειρηματικός Αυτοματισμός' }, price: { EN: 'From €50/month', GR: 'Από €50/μήνα' },
    best: { EN: 'Any business with manual admin', GR: 'Κάθε επιχείρηση με χειροκίνητο admin' },
    desc: { EN: 'Connect forms, emails and WhatsApp enquiries so you stop copying and chasing information.', GR: 'Συνδέει φόρμες, emails και αιτήματα WhatsApp ώστε να σταματήσετε την αντιγραφή και το κυνήγι πληροφοριών.' } },
  'ai-customer-journey': { group: 'automation', icon: 'Route', amount: 75, recurring: true, unit: 'month',
    label: { EN: 'AI Customer Journey', GR: 'AI Διαδρομή Πελάτη' }, price: { EN: 'From €75/month', GR: 'Από €75/μήνα' },
    best: { EN: 'Businesses wanting end-to-end flow', GR: 'Επιχειρήσεις που θέλουν ολοκληρωμένη ροή' },
    desc: { EN: 'A smarter journey from website visit to enquiry, proposal, follow-up and conversion.', GR: 'Μια εξυπνότερη διαδρομή από την επίσκεψη στο site έως το αίτημα, την πρόταση, το follow-up και τη μετατροπή.' } },

  // ── SUPPORT & GROWTH ──────────────────────────────────────────────────────
  'hosting-care': { group: 'support', icon: 'ShieldCheck', amount: 20, recurring: true, unit: 'month',
    label: { EN: 'Hosting and Website Care', GR: 'Φιλοξενία & Συντήρηση' }, price: { EN: '€20/month', GR: '€20/μήνα' },
    best: { EN: 'Most businesses', GR: 'Οι περισσότερες επιχειρήσεις' },
    desc: { EN: 'Hosting, security, backups and basic updates fully managed for you.', GR: 'Φιλοξενία, ασφάλεια, backups και βασικές ενημερώσεις, πλήρως διαχειριζόμενα.' } },
  'extra-storage': { group: 'support', icon: 'Database', amount: 10, recurring: true, unit: 'month',
    label: { EN: 'Extra Storage', GR: 'Επιπλέον Αποθηκευτικός Χώρος' }, price: { EN: '€10/month', GR: '€10/μήνα' },
    best: { EN: 'Image & media-heavy sites', GR: 'Sites με πολλές εικόνες & media' },
    desc: { EN: 'Additional storage for media-rich websites and galleries.', GR: 'Επιπλέον χώρος για sites με πολλά media και gallery.' } },
  'priority-updates': { group: 'support', icon: 'Zap', amount: 50, recurring: true, unit: 'month',
    label: { EN: 'Priority Updates', GR: 'Ενημερώσεις Προτεραιότητας' }, price: { EN: '€50/month', GR: '€50/μήνα' },
    best: { EN: 'Businesses that change often', GR: 'Επιχειρήσεις με συχνές αλλαγές' },
    desc: { EN: 'Faster turnaround on website content changes and requests.', GR: 'Ταχύτερη εξυπηρέτηση σε αλλαγές και αιτήματα περιεχομένου.' } },
  'content-refresh': { group: 'support', icon: 'PenLine', amount: 100, recurring: true, unit: 'month',
    label: { EN: 'Monthly Content Refresh', GR: 'Μηνιαία Ανανέωση Περιεχομένου' }, price: { EN: '€100/month', GR: '€100/μήνα' },
    best: { EN: 'Seasonal & active businesses', GR: 'Εποχικές & ενεργές επιχειρήσεις' },
    desc: { EN: 'Regular content updates to keep your website current and relevant.', GR: 'Τακτικές ενημερώσεις για να μένει το site σας επίκαιρο.' } },
  'website-health-check': { group: 'support', icon: 'Activity', amount: 75, recurring: false, unit: 'oneoff',
    label: { EN: 'Website Health Check', GR: 'Έλεγχος Υγείας Ιστοσελίδας' }, price: { EN: '€75 one-off', GR: '€75 εφάπαξ' },
    best: { EN: 'Existing websites', GR: 'Υπάρχουσες ιστοσελίδες' },
    desc: { EN: 'A full review of speed, SEO and conversion with clear recommendations.', GR: 'Πλήρης έλεγχος ταχύτητας, SEO και μετατροπών με ξεκάθαρες προτάσεις.' } },
  'domain-connection': { group: 'support', icon: 'Globe', amount: 50, recurring: false, unit: 'oneoff',
    label: { EN: 'Domain Connection', GR: 'Σύνδεση Domain' }, price: { EN: '€50 one-off', GR: '€50 εφάπαξ' },
    best: { EN: 'New website launches', GR: 'Νέες εκκινήσεις ιστοσελίδων' },
    desc: { EN: 'Connect and configure your domain correctly with your new website.', GR: 'Σύνδεση και σωστή ρύθμιση του domain σας με το νέο site.' } },
  'business-email': { group: 'support', icon: 'AtSign', amount: 50, recurring: false, unit: 'oneoff',
    label: { EN: 'Business Email Setup', GR: 'Στήσιμο Επαγγελματικού Email' }, price: { EN: '€50 one-off', GR: '€50 εφάπαξ' },
    best: { EN: 'Professional communication', GR: 'Επαγγελματική επικοινωνία' },
    desc: { EN: 'Set up professional business email on your own domain.', GR: 'Στήσιμο επαγγελματικού email στο δικό σας domain.' } },
  'tracking-setup': { group: 'support', icon: 'LineChart', amount: 75, recurring: false, unit: 'oneoff',
    label: { EN: 'Tracking Setup', GR: 'Στήσιμο Tracking' }, price: { EN: '€75 one-off', GR: '€75 εφάπαξ' },
    best: { EN: 'Businesses running ads', GR: 'Επιχειρήσεις που τρέχουν διαφημίσεις' },
    desc: { EN: 'Analytics and conversion tracking set up so every enquiry is measured.', GR: 'Στήσιμο analytics και conversion tracking ώστε να μετριέται κάθε αίτημα.' } },
};

export const NOT_SURE = 'not-sure';

export const GROUP_ORDER = ['website', 'digital', 'marketing', 'automation', 'support'];
export const GROUPS = { website: [], digital: [], marketing: [], automation: [], support: [] };
Object.keys(CATALOG).forEach((id) => { GROUPS[CATALOG[id].group].push(id); });

export const GROUP_TITLES = {
  website:    { EN: 'Website Design & Build',  GR: 'Σχεδιασμός & Κατασκευή Ιστοσελίδων' },
  digital:    { EN: 'Digital Services',         GR: 'Ψηφιακές Υπηρεσίες' },
  marketing:  { EN: 'Digital Marketing',        GR: 'Ψηφιακό Marketing' },
  automation: { EN: 'Automation',               GR: 'Αυτοματισμοί' },
  support:    { EN: 'Support & Growth',         GR: 'Υποστήριξη & Ανάπτυξη' },
};
export const GROUP_ICONS = {
  website:    'Layout',
  digital:    'Sparkles',
  marketing:  'TrendingUp',
  automation: 'Bot',
  support:    'ShieldCheck',
};

const FEATURES = {
  'basic-launch-website': { EN: ['Professional one/multi-page site', 'Mobile responsive design', 'Contact form or WhatsApp CTA', 'Basic SEO setup'], GR: ['Επαγγελματικό site', 'Responsive σχεδιασμός', 'Φόρμα ή WhatsApp CTA', 'Βασικό SEO'] },
  'business-website': { EN: ['Multi-page structure', 'Lead / enquiry flow', 'FAQ & content sections', 'Improved SEO structure', 'Automation-ready'], GR: ['Δομή πολλών σελίδων', 'Ροή αιτημάτων', 'FAQ & ενότητες περιεχομένου', 'Βελτιωμένο SEO', 'Έτοιμο για αυτοματισμούς'] },
  'growth-website': { EN: ['Advanced multi-page structure', 'Conversion-optimised pages', 'SEO foundations', 'Automation-ready setup', 'Lead generation focus'], GR: ['Προηγμένη δομή πολλών σελίδων', 'Βελτιστοποιημένες σελίδες μετατροπών', 'Θεμέλια SEO', 'Έτοιμο για αυτοματισμούς', 'Εστίαση στο lead generation'] },
  'premium-ai-website': { EN: ['Premium custom design', 'Stronger customer journey', 'AI assistant support', 'Automation-ready sections', 'Scalable growth setup'], GR: ['Premium custom σχεδιασμός', 'Ισχυρότερη διαδρομή πελάτη', 'Υποστήριξη AI βοηθού', 'Έτοιμες ενότητες αυτοματισμού', 'Κλιμακούμενη ανάπτυξη'] },
  'whatsapp-automation': { EN: ['WhatsApp click-to-chat setup', 'Pre-filled enquiry messages', 'Customer question flow', 'Basic automated replies', 'Lead capture and handover', 'Booking / proposal routing'], GR: ['Στήσιμο click-to-chat WhatsApp', 'Προ-συμπληρωμένα μηνύματα', 'Ροή ερωτήσεων πελάτη', 'Βασικές αυτόματες απαντήσεις', 'Λήψη & παράδοση leads', 'Δρομολόγηση κράτησης / πρότασης'] },
  'ai-chatbot': { EN: ['Website chatbot', 'FAQ handling', 'Lead qualification', 'Service recommendation', 'WhatsApp / email handover', 'Booking enquiry support'], GR: ['Chatbot ιστοσελίδας', 'Διαχείριση FAQ', 'Αξιολόγηση leads', 'Πρόταση υπηρεσιών', 'Παράδοση σε WhatsApp / email', 'Υποστήριξη αιτημάτων κράτησης'] },
  'ai-proposal-generation': { EN: ['Auto-generated proposals', 'Personalised per client', 'Pricing table included', 'Sent via WhatsApp or email'], GR: ['Αυτόματες προτάσεις', 'Εξατομίκευση ανά πελάτη', 'Πίνακας τιμών', 'Αποστολή μέσω WhatsApp ή email'] },
  'email-automation': { EN: ['Welcome sequence', 'Follow-ups & reminders', 'Review requests', 'Newsletter template'], GR: ['Ακολουθία καλωσορίσματος', 'Follow-up & υπενθυμίσεις', 'Αιτήματα αξιολόγησης', 'Πρότυπο newsletter'] },
  'local-seo-setup': { EN: ['Google Business optimisation', 'Local keyword targeting', 'Technical SEO', 'One-off setup report'], GR: ['Βελτιστοποίηση Google Business', 'Στόχευση τοπικών λέξεων', 'Τεχνικό SEO', 'Εφάπαξ έκθεση setup'] },
  'hosting-care': { EN: ['Reliable hosting', 'Security & backups', 'Basic updates', 'Managed for you'], GR: ['Αξιόπιστη φιλοξενία', 'Ασφάλεια & backups', 'Βασικές ενημερώσεις', 'Διαχείριση από εμάς'] },
};

export function catFeatures(id, lang) { const f = FEATURES[id]; return f ? (f[lang] || f.EN) : null; }
export function cat(id) { return CATALOG[id] || null; }
export function catLabel(id, lang, T) {
  if (id === NOT_SURE) return T && T[lang] ? T[lang].not_sure : 'Not sure yet';
  const c = CATALOG[id]; return c ? c.label[lang] : id;
}
export function catPrice(id, lang) { const c = CATALOG[id]; return c ? c.price[lang] : ''; }
export function catAmount(id) { const c = CATALOG[id]; return c ? c.amount : 0; }
export function catRecurring(id) { const c = CATALOG[id]; return c ? !!c.recurring : false; }
